security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_MODERATOR
        ROLE_MODERATOR: ROLE_USER

    providers:
        database_users:
            entity: 
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern:  ^/login_admin
            stateless: false
            anonymous: false
            json_login:
                check_path: /login_admin
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            pattern:   ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login_admin, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/(docs.jsonld|contexts/Entrypoint), methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/.+, roles: ROLE_ADMIN }
        - { path: ^/, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
