clearBasket:
    path: /payment/clear
    methods: [GET]
    controller: App\Controller\Files::paymentFile_clear

contact:
    path: /contact
    methods: [GET]
    controller: App\Controller\Contact

contactAction:
    path: /contact/send
    methods: [POST]
    controller: App\Action\Contact

fileList:
    path: /files
    methods: [GET]
    controller: App\Controller\Files::listFiles

login:
  path: /login_admin

setImageFile:
    path: /files/setImage
    methods: [GET]
    controller: App\Controller\Files::setImageFile

payment_get:
    path: /payment
    methods: [GET]
    controller: App\Controller\Files::paymentFile_get

payment_post:
    path: /payment
    methods: [POST]
    controller: App\Controller\Files::paymentFile_post

validation_payment:
    path: /validatePayment
    methods: [POST]
    controller: App\Action\Payment

mentions:
    path: /mentions
    methods: [GET]
    controller: App\Controller\Mentions

generate:
    path: /generate
    controller: App\Controller\Welcome::generate

downloadFile:
    path: /download/{token}
    controller: App\Controller\Download

uploadFile:
    methods: [POST]
    path: /upload/files
    controller: App\Action\File

notify:
    methods: [POST]
    path: /notify
    controller: App\Action\Notify

updateFile:
    methods: [POST]
    path: /update/files
    controller: App\Action\File::update

welcome:
    path: /
    methods: [GET]
    controller: App\Controller\Welcome

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'
